#line 2 "cfg-lexer.c"

#line 4 "cfg-lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cfg__create_buffer
#define yy_delete_buffer cfg__delete_buffer
#define yy_flex_debug cfg__flex_debug
#define yy_init_buffer cfg__init_buffer
#define yy_flush_buffer cfg__flush_buffer
#define yy_load_buffer_state cfg__load_buffer_state
#define yy_switch_to_buffer cfg__switch_to_buffer
#define yyin cfg_in
#define yyleng cfg_leng
#define yylex cfg_lex
#define yylineno cfg_lineno
#define yyout cfg_out
#define yyrestart cfg_restart
#define yytext cfg_text
#define yywrap cfg_wrap
#define yyalloc cfg_alloc
#define yyrealloc cfg_realloc
#define yyfree cfg_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cfg_restart(cfg_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t cfg_leng;

extern FILE *cfg_in, *cfg_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE cfg_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-cfg_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < cfg_leng; ++yyl )\
                    if ( cfg_text[yyl] == '\n' )\
                        --cfg_lineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --cfg_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cfg_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cfg_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cfg_restart()), so that the user can continue scanning by
	 * just pointing cfg_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cfg_text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t cfg_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow cfg_wrap()'s to do buffer switches
 * instead of setting up a fresh cfg_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void cfg_restart (FILE *input_file  );
void cfg__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cfg__create_buffer (FILE *file,int size  );
void cfg__delete_buffer (YY_BUFFER_STATE b  );
void cfg__flush_buffer (YY_BUFFER_STATE b  );
void cfg_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void cfg_pop_buffer_state (void );

static void cfg_ensure_buffer_stack (void );
static void cfg__load_buffer_state (void );
static void cfg__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cfg__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cfg__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cfg__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cfg__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *cfg_alloc (yy_size_t  );
void *cfg_realloc (void *,yy_size_t  );
void cfg_free (void *  );

#define yy_new_buffer cfg__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cfg_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cfg__create_buffer(cfg_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cfg_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cfg__create_buffer(cfg_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cfg_wrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *cfg_in = (FILE *) 0, *cfg_out = (FILE *) 0;

typedef int yy_state_type;

extern int cfg_lineno;

int cfg_lineno = 1;

extern char *cfg_text;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr cfg_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cfg_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	cfg_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 25
#define YY_END_OF_BUFFER 26
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[286] =
    {   0,
        0,    0,   26,   24,   21,   21,   24,   24,    1,    1,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   21,    0,
       22,    0,    0,    0,    0,    0,    0,   20,    1,   23,
       23,   23,   23,   23,    5,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,    0,    0,    0,    0,    0,
        1,    3,   23,   23,   23,    5,   23,   23,   23,   23,
       23,   23,   10,   23,   23,   12,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,    0,    0,

        0,    0,    0,    1,    3,   23,   23,   23,    5,    0,
       23,    0,    8,   23,    0,   23,   23,   23,   23,   23,
       17,   23,   23,   23,   23,   23,    0,    0,   23,   23,
        0,    9,    0,    0,    1,    3,   23,   23,   19,    5,
        0,   23,    0,   23,    0,   23,   23,   23,   23,   23,
       23,   23,   23,    0,    0,    0,    0,    0,   23,    0,
        0,    1,    3,   23,   23,    5,    0,    0,    0,   23,
        0,   23,   14,   23,   23,   23,   23,   23,    0,    0,
        0,    0,    0,    0,    0,    1,    3,   23,    7,    5,
        0,    0,    8,   23,    0,   23,    0,   18,   23,   23,

        0,   11,    0,    0,    0,    0,    0,    0,    1,    3,
       23,    5,    0,    0,   23,    0,    0,   23,   23,    0,
        0,    0,   15,   16,    0,    0,    1,    3,   23,    5,
        0,    0,   12,    0,   23,    0,    0,   11,    0,    0,
        0,    1,    3,    5,    0,    0,   23,    0,    0,    0,
        2,    4,    5,    0,    0,   13,    2,    4,    5,    0,
        0,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    6,    6,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    1,    1,    7,    8,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,    1,
        1,    1,    1,    1,   10,   10,   10,   10,   11,   10,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   13,   12,   12,   12,   12,   12,   12,   12,
        1,    1,    1,    1,    1,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,   12,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   12,   35,
       36,   37,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[38] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst flex_uint16_t yy_base[289] =
    {   0,
        0,    0,  505,  506,   36,   38,   38,  501,   36,   39,
        0,  477,  484,  470,   43,   25,  475,  477,  468,  475,
       40,  468,  468,   41,  476,  477,   50,  474,   54,  487,
      506,   56,   58,   59,   69,   70,  487,  506,   77,    0,
       96,  472,  472,  451,   74,  466,  458,  451,  459,  468,
      457,  451,   56,  463,  453,  444,  444,  445,  450,  441,
       74,  444,  443,  448,  443,   48,   73,   89,   71,   90,
       90,  120,  455,  435,  440,  101,  459,  448,   89,  441,
      456,  443,    0,  428,  427,    0,  431,  435,  424,  433,
      440,  421,  429,  434,  444,  443,  413,  430,  117,  442,

       97,  112,  441,  116,  139,  426,  421,  426,  111,  423,
      417,  417,    0,  412,  420,  410,  417,  410,  403,  405,
        0,  417,  398,  402,  422,  421,  405,  404,  418,  396,
      418,  506,  129,  128,  134,  152,  405,  393,    0,  157,
      393,  412,  387,  399,  397,  400,  387,  394,  375,  384,
      394,  386,  377,  374,  388,  377,  376,  371,  371,  168,
      169,  167,  188,  368,  373,  170,  381,  366,  367,  377,
      370,  368,    0,  386,  360,  368,  362,  178,  366,  369,
      355,  354,  357,  379,  176,  178,  203,  360,    0,  174,
      359,  352,  506,  349,  364,  359,  358,    0,  351,  348,

      342,    0,  347,  347,  338,  337,  352,  188,  181,  216,
      340,  193,  352,  347,  333,  327,  336,  339,  354,  337,
      340,  343,  506,  506,  333,  212,  229,  236,  329,  221,
      328,  335,  506,  335,  319,  318,  312,  506,  312,  329,
      342,  232,  249,  241,  328,  322,  307,  320,  323,  308,
      262,  265,  254,  321,  168,  506,  278,    0,  270,  165,
      161,  281,  283,  285,  287,  289,  291,  293,  295,  297,
      299,  301,  303,  305,  307,  309,  311,  313,  315,  317,
      319,  321,  323,  325,  506,  333,  336,  141
    } ;

static yyconst flex_int16_t yy_def[289] =
    {   0,
      285,    1,  285,  285,  285,  285,  286,  287,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  285,  286,
      285,  286,  286,  286,  286,  286,  287,  285,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  286,  286,  286,  286,  286,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  286,  286,

      286,  286,  286,  288,  288,  288,  288,  288,  288,  285,
      288,  285,  288,  288,  285,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  285,  285,  288,  288,
      286,  285,  286,  286,  288,  288,  288,  288,  288,  288,
      285,  288,  285,  288,  285,  288,  288,  288,  288,  288,
      288,  288,  288,  285,  285,  285,  285,  285,  288,  286,
      286,  288,  288,  288,  288,  288,  285,  285,  285,  288,
      285,  288,  288,  288,  288,  288,  288,  288,  285,  285,
      285,  285,  285,  286,  286,  288,  288,  288,  288,  288,
      285,  285,  285,  288,  285,  288,  285,  288,  288,  288,

      285,  288,  285,  285,  285,  285,  285,  286,  288,  288,
      288,  288,  285,  285,  288,  285,  285,  288,  288,  285,
      285,  285,  285,  285,  285,  286,  288,  288,  288,  288,
      285,  285,  285,  285,  288,  285,  285,  285,  285,  285,
      286,  288,  288,  288,  285,  285,  288,  285,  285,  285,
      288,  288,  288,  285,  285,  285,  288,  252,  288,  285,
      285,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,    0,  285,  285,  285
    } ;

static yyconst flex_uint16_t yy_nxt[544] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   10,   11,
       12,   11,   13,   14,   15,   16,   17,   11,   18,   11,
       11,   19,   11,   20,   21,   11,   22,   23,   11,   24,
       25,   26,   27,   28,   11,   11,   11,   29,   29,   29,
       29,   31,   39,   39,   39,   39,   39,   39,   47,   45,
       45,   31,   48,   54,   32,   29,   29,   55,   59,   31,
       49,   31,   31,   33,   46,   34,   63,   60,   35,   36,
       41,   56,   31,   31,   31,   64,   31,   66,   99,   67,
       76,   76,   68,   71,   71,   71,   84,   85,  100,   92,
       69,   93,   31,   31,  112,  102,  104,  104,  104,   94,

       31,   70,   72,   72,   72,   72,   72,  109,  109,   72,
       72,   72,   72,   72,   72,   31,  133,  140,  140,  113,
       31,  101,  135,  135,  135,  103,  105,  105,  105,  105,
      105,   31,   31,  105,  105,  105,  105,  105,  105,  131,
      162,  162,  162,   40,  134,  136,  136,  136,  136,  136,
      160,  161,  136,  136,  136,  136,  136,  136,  163,  163,
      163,  163,  163,  166,  166,  163,  163,  163,  163,  163,
      163,   31,   31,  186,  186,  186,  190,  190,  238,   31,
      212,  212,  185,  201,  209,  209,  209,  227,  227,  227,
      193,   31,  261,  184,  187,  187,  187,  187,  187,  230,

      230,  187,  187,  187,  187,  187,  187,  208,  202,  210,
      210,  210,  210,  210,  226,   31,  210,  210,  210,  210,
      210,  210,  228,  228,  228,  228,  228,  244,  244,  228,
      228,  228,  228,  228,  228,  242,  242,  242,  251,  251,
      251,  241,  243,  243,  243,  243,  243,  253,  253,  243,
      243,  243,  243,  243,  243,  252,  252,  252,  252,  252,
      259,  259,  252,  252,  252,  252,  252,  252,  257,  257,
      257,  258,  258,  258,  258,  258,  262,  262,  258,  258,
      258,  258,  258,  258,  257,  257,  257,  263,  263,  264,
      264,  265,  265,  266,  266,  267,  267,  268,  268,  269,

      269,  270,  270,  271,  271,  272,  272,  273,  273,  274,
      274,  275,  275,  276,  276,  277,  277,  278,  278,  279,
      279,  280,  280,  281,  281,  282,  282,  283,  283,  284,
      284,  284,  284,   30,  260,   30,   37,   37,   37,  256,
      238,  255,   86,  254,  193,  132,  250,  233,  249,  248,
      247,  246,  245,  193,  189,  240,  239,  238,  237,  236,
      235,  234,  233,  202,  232,  231,  229,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  202,  216,  215,  214,
      213,  211,  132,  207,  206,  205,  204,  203,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  189,  188,

       83,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      113,  174,  173,  172,  171,  170,  169,  168,  167,  165,
      164,  132,  159,  158,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  146,  145,  144,  143,  142,
      141,  139,  138,  137,  132,  132,  130,  129,  128,  127,
      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  111,  110,  108,  107,  106,   98,   97,
       96,   95,   91,   90,   89,   88,   86,   87,   86,   83,
       82,   81,   80,   79,   78,   77,   75,   74,   73,   38,
       31,   65,   62,   61,   58,   57,   53,   52,   51,   50,

       44,   43,   42,   38,  285,    3,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285
    } ;

static yyconst flex_int16_t yy_chk[544] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    6,
        6,    7,    9,    9,    9,   10,   10,   10,   16,   15,
       15,   66,   16,   21,    7,   29,   29,   21,   24,   32,
       16,   33,   34,    7,   15,    7,   27,   24,    7,    7,
        9,   21,   35,   36,   69,   27,   67,   32,   66,   33,
       45,   45,   34,   39,   39,   39,   53,   53,   67,   61,
       35,   61,   68,   70,   79,   69,   71,   71,   71,   61,

      101,   36,   41,   41,   41,   41,   41,   76,   76,   41,
       41,   41,   41,   41,   41,  102,  101,  109,  109,   79,
       99,   68,  104,  104,  104,   70,   72,   72,   72,   72,
       72,  134,  133,   72,   72,   72,   72,   72,   72,   99,
      135,  135,  135,  288,  102,  105,  105,  105,  105,  105,
      133,  134,  105,  105,  105,  105,  105,  105,  136,  136,
      136,  136,  136,  140,  140,  136,  136,  136,  136,  136,
      136,  160,  161,  162,  162,  162,  166,  166,  261,  185,
      190,  190,  161,  178,  186,  186,  186,  209,  209,  209,
      260,  208,  255,  160,  163,  163,  163,  163,  163,  212,

      212,  163,  163,  163,  163,  163,  163,  185,  178,  187,
      187,  187,  187,  187,  208,  226,  187,  187,  187,  187,
      187,  187,  210,  210,  210,  210,  210,  230,  230,  210,
      210,  210,  210,  210,  210,  227,  227,  227,  242,  242,
      242,  226,  228,  228,  228,  228,  228,  244,  244,  228,
      228,  228,  228,  228,  228,  243,  243,  243,  243,  243,
      253,  253,  243,  243,  243,  243,  243,  243,  251,  251,
      251,  252,  252,  252,  252,  252,  259,  259,  252,  252,
      252,  252,  252,  252,  257,  257,  257,  262,  262,  263,
      263,  264,  264,  265,  265,  266,  266,  267,  267,  268,

      268,  269,  269,  270,  270,  271,  271,  272,  272,  273,
      273,  274,  274,  275,  275,  276,  276,  277,  277,  278,
      278,  279,  279,  280,  280,  281,  281,  282,  282,  283,
      283,  284,  284,  286,  254,  286,  287,  287,  287,  250,
      249,  248,  247,  246,  245,  241,  240,  239,  237,  236,
      235,  234,  232,  231,  229,  225,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  211,  207,  206,  205,
      204,  203,  201,  200,  199,  197,  196,  195,  194,  192,
      191,  188,  184,  183,  182,  181,  180,  179,  177,  176,
      175,  174,  172,  171,  170,  169,  168,  167,  165,  164,

      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  138,
      137,  131,  130,  129,  128,  127,  126,  125,  124,  123,
      122,  120,  119,  118,  117,  116,  115,  114,  112,  111,
      110,  108,  107,  106,  103,  100,   98,   97,   96,   95,
       94,   93,   92,   91,   90,   89,   88,   87,   85,   84,
       82,   81,   80,   78,   77,   75,   74,   73,   65,   64,
       63,   62,   60,   59,   58,   57,   56,   55,   54,   52,
       51,   50,   49,   48,   47,   46,   44,   43,   42,   37,
       30,   28,   26,   25,   23,   22,   20,   19,   18,   17,

       14,   13,   12,    8,    3,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[26] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 1, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cfg__flex_debug;
int cfg__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cfg_text;
#line 1 "cfg-lexer.l"
/* -*- fundamental -*- (for emacs) */
/* these are needed so that two lexers can be linked to same binary */
#define YY_NO_INPUT 1
#line 11 "cfg-lexer.l"

#include "includes.h"
#include "cfg-parser.h"

#line 732 "cfg-lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cfg_lex_destroy (void );

int cfg_get_debug (void );

void cfg_set_debug (int debug_flag  );

YY_EXTRA_TYPE cfg_get_extra (void );

void cfg_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *cfg_get_in (void );

void cfg_set_in  (FILE * _in_str  );

FILE *cfg_get_out (void );

void cfg_set_out  (FILE * _out_str  );

yy_size_t cfg_get_leng (void );

char *cfg_get_text (void );

int cfg_get_lineno (void );

void cfg_set_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cfg_wrap (void );
#else
extern int cfg_wrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( cfg_text, cfg_leng, 1, cfg_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( cfg_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( cfg_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, cfg_in))==0 && ferror(cfg_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(cfg_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cfg_lex (void);

#define YY_DECL int cfg_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cfg_text and cfg_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! cfg_in )
			cfg_in = stdin;

		if ( ! cfg_out )
			cfg_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cfg_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cfg__create_buffer(cfg_in,YY_BUF_SIZE );
		}

		cfg__load_buffer_state( );
		}

	{
#line 21 "cfg-lexer.l"



#line 952 "cfg-lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cfg_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 286 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 506 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < cfg_leng; ++yyl )
				if ( cfg_text[yyl] == '\n' )
					   
    cfg_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 24 "cfg-lexer.l"
{
    cfg_lval.intvalue=(unsigned int) atoi(cfg_text);
    return INTEGER32;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "cfg-lexer.l"
{
    printf("Decimal constant '%s' is too long (> 32 bits)\n",
           cfg_text);
    return ERROR;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 35 "cfg-lexer.l"
{
    sscanf(cfg_text+2, "%x", &cfg_lval.intvalue);
    return INTEGER32;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "cfg-lexer.l"
{
    printf("Hexadecimal constant '%s' is too long (> 32 bits)\n",
           cfg_text);
     return ERROR;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "cfg-lexer.l"
{
			int i;
			/*printf("Integer: %s (%u)\n", cfg_text,
				strtol(cfg_text+1, NULL, 2));*/
			
			i = strlen(cfg_text+1) -1;
			cfg_lval.intvalue=0;
			while(*(++cfg_text) != 0) { 
				if(*cfg_text == '1') {
					cfg_lval.intvalue += 1 << i;
				}
				i--;
			}
			return INTEGER32;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "cfg-lexer.l"
{
    printf("Binary constant '%s' too is too long (> 32 bits)\n",
           cfg_text);
    return ERROR;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 68 "cfg-lexer.l"
{
    if (!strcmp(cfg_text, "Section"))
        return SECTION;
    else
        return ENDSECTION;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 76 "cfg-lexer.l"
{
    if (!strcmp(cfg_text, "clock-speed"))
        return CLOCKSPEED;
    else if (!strcmp(cfg_text, "memory"))
        return MEMORY;
    else if (!strcmp(cfg_text, "cpu-irq"))
        return CPUIRQ;
    else if (!strcmp(cfg_text, "big-endian"))
        return BIGENDIAN;
    else if (!strcmp(cfg_text, "little-endian"))
        return LITTLEENDIAN;
    else
        return CPUS;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 91 "cfg-lexer.l"
{
    if (!strcmp(cfg_text, "\"simulator\""))
        return SIMULATOR;
    else if (!strcmp(cfg_text, "\"disk\""))
        return DISK;
    else if (!strcmp(cfg_text, "\"tty\""))
        return TTY;
    else if (!strcmp(cfg_text, "\"nic\""))
        return NIC;
    else
        return PLUGIN;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 104 "cfg-lexer.l"
{
    if (!strcmp(cfg_text, "vendor"))
        return VENDOR;
    else
        return IRQ;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 111 "cfg-lexer.l"
{
    if (!strcmp(cfg_text, "sector-size"))
        return SECTORSIZE;
    else if (!strcmp(cfg_text, "sectors"))
        return NUMSECTORS;
    else if (!strcmp(cfg_text, "cylinders"))
        return CYLINDERS;
    else if (!strcmp(cfg_text, "rotation-time"))
        return ROTTIME;
    else if (!strcmp(cfg_text, "seek-time"))
        return SEEKTIME;
    else
        return FILENAME;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 126 "cfg-lexer.l"
{
    if (!strcmp(cfg_text, "mtu"))
        return MTU;
    else if (!strcmp(cfg_text, "mac"))
        return MAC;
    else if (!strcmp(cfg_text, "reliability"))
        return RELIABILITY;
    else if (!strcmp(cfg_text, "dma-delay"))
        return DMADELAY;
    else
        return SENDDELAY;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 139 "cfg-lexer.l"
{
    return UNIXSOCKET;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 143 "cfg-lexer.l"
{
    return SOCKETLISTEN;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 147 "cfg-lexer.l"
{
    return TCPHOST;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 151 "cfg-lexer.l"
{
    return UDPHOST;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 155 "cfg-lexer.l"
{
    return PORT;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 159 "cfg-lexer.l"
{
    return OPTIONS;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 163 "cfg-lexer.l"
{
    return ASYNC;
}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 167 "cfg-lexer.l"
/* ignore comments */
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 169 "cfg-lexer.l"
/* eat up whitespace */
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 173 "cfg-lexer.l"
{
    /* XXX: add '"' escaping */

    /* copy and remove leading and trailing " */
    cfg_lval.stringvalue=strdup(cfg_text+1);
    cfg_lval.stringvalue[strlen(cfg_lval.stringvalue)-1] = 0;
    return STRING;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 183 "cfg-lexer.l"
{
    printf("Invalid keyword: '%s'\n", cfg_text);
    return ERROR;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 189 "cfg-lexer.l"
{
    printf("%s\n", cfg_text);
    return ERROR;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 195 "cfg-lexer.l"
ECHO;
	YY_BREAK
#line 1263 "cfg-lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed cfg_in at a new source and called
			 * cfg_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = cfg_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( cfg_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cfg_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of cfg_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cfg_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cfg_restart(cfg_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cfg_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 286 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 286 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 285);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cfg_restart(cfg_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cfg_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cfg_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    cfg_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cfg_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        cfg_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cfg__create_buffer(cfg_in,YY_BUF_SIZE );
	}

	cfg__init_buffer(YY_CURRENT_BUFFER,input_file );
	cfg__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cfg__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cfg_pop_buffer_state();
	 *		cfg_push_buffer_state(new_buffer);
     */
	cfg_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cfg__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (cfg_wrap()) processing, but the only time this flag
	 * is looked at is after cfg_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void cfg__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	cfg_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cfg__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cfg_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cfg__create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cfg_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cfg__create_buffer()" );

	b->yy_is_our_buffer = 1;

	cfg__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cfg__create_buffer()
 * 
 */
    void cfg__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cfg_free((void *) b->yy_ch_buf  );

	cfg_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cfg_restart() or at EOF.
 */
    static void cfg__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cfg__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cfg__init_buffer was _probably_
     * called from cfg_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void cfg__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cfg__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void cfg_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	cfg_ensure_buffer_stack();

	/* This block is copied from cfg__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cfg__switch_to_buffer. */
	cfg__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void cfg_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cfg__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cfg__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cfg_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; // After all that talk, this was set to 1 anyways...
		(yy_buffer_stack) = (struct yy_buffer_state**)cfg_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cfg_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)cfg_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cfg_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cfg__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cfg_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cfg__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cfg__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cfg_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cfg__scan_bytes() instead.
 */
YY_BUFFER_STATE cfg__scan_string (yyconst char * yystr )
{
    
	return cfg__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cfg_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cfg__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cfg_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cfg__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cfg__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cfg__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cfg_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cfg_text[cfg_leng] = (yy_hold_char); \
		(yy_c_buf_p) = cfg_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		cfg_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int cfg_get_lineno  (void)
{
        
    return cfg_lineno;
}

/** Get the input stream.
 * 
 */
FILE *cfg_get_in  (void)
{
        return cfg_in;
}

/** Get the output stream.
 * 
 */
FILE *cfg_get_out  (void)
{
        return cfg_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t cfg_get_leng  (void)
{
        return cfg_leng;
}

/** Get the current token.
 * 
 */

char *cfg_get_text  (void)
{
        return cfg_text;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void cfg_set_lineno (int  _line_number )
{
    
    cfg_lineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see cfg__switch_to_buffer
 */
void cfg_set_in (FILE *  _in_str )
{
        cfg_in = _in_str ;
}

void cfg_set_out (FILE *  _out_str )
{
        cfg_out = _out_str ;
}

int cfg_get_debug  (void)
{
        return cfg__flex_debug;
}

void cfg_set_debug (int  _bdebug )
{
        cfg__flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cfg_lex_destroy(), so don't allocate here.
     */

    /* We do not touch cfg_lineno unless the option is enabled. */
    cfg_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    cfg_in = stdin;
    cfg_out = stdout;
#else
    cfg_in = (FILE *) 0;
    cfg_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cfg_lex_init()
     */
    return 0;
}

/* cfg_lex_destroy is for both reentrant and non-reentrant scanners. */
int cfg_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cfg__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cfg_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	cfg_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cfg_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cfg_alloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *cfg_realloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cfg_free (void * ptr )
{
			free( (char *) ptr );	/* see cfg_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 195 "cfg-lexer.l"




